name: time-series-analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - pip
  - pip:
      - yfinance
      - pandas_market_calendars
      - python-bcb
