[project]
name = "time-series-analysis"
version = "0.1.0"
description = "A comprehensive, hands-on guide to time series analysis, forecasting, and temporal machine learning using Python."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "yfinance",
    "pandas_market_calendars",
    "python-bcb",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["ts*"]
